version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - api
    ports:
      - 80:80
      - 443:443
    environment:
      - API_URL=/api
    volumes:
      - /data/certs:/etc/nginx/certs
      - ./api/uploads:/var/www/api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 7777:80
    environment:
      - WEB_PORT=80
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=lashmaker
      - JWT_SECRET=secret
      - MAIL_USER=kaprisa57@gmail.com
      - MAIL_PASSWORD=kseniya5k
    volumes:
      - ./api/uploads:/opt/api/uploads
  mysql:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3380:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./sql/data:/var/lib/mysql
      - ./sql/init:/docker-entrypoint-initdb.d/:ro
